package com.cloudframe.app.common;
import com.cloudframe.app.utility.CFUtil;
/* Java Code Generated by CloudFrame */
public class CONSTANTS {
	/* final variables */
	public static final char[] SPACE = " ".toCharArray();
	public static final char[] ZERO = "0".toCharArray();
	public static final char[] SPACE_50 = CFUtil.fillSpaces(50) ;
	public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray() ;
	public static final char[] FORMAT1016334848 = "----".toCharArray() ;
	public static final char[] FORMAT_1287115115 = "ZZZZ9.99".toCharArray() ;
	public static final char[] FORMAT_1059277505 = "ZZZ9".toCharArray() ;
	public static final char[] LITERAL_CF04WIDG_B_1 = "CF04WIDG 1".toCharArray() ;
	public static final char[] LITERAL_1118165632 = "**************************************************".toCharArray() ;
	public static final char[] LITERAL_375072441 = "WIDGET Not found !!                               ".toCharArray() ;
	public static final char[] LITERAL_1548266813 = "WIDGET lookup failed : sqlcode = ".toCharArray() ;
	public static final char[] LITERAL_SIZE = "SIZE".toCharArray() ;
}
