package com.cloudframe.app.common;

/* Java Code Generated by CloudFrame */ 
public class SQLS {
	public static final char[] SQL_1714023506 = "SELECT WIDGET_COLOR , WIDGET_SIZE , WIDGET_PRICE , WIDGET_SUPPLIER , WIDGET_DESC , WIDGET_MANU_PLANT , WIDGET_MANU_COST , WIDGET_LEAD_TIME FROM TBWIDGET WHERE WIDGET_NUM = ?".toCharArray() ;
}
