package com.edwardjones.app.common;
/* Java Code Generated by CloudFrame */ 
import com.cloudframe.app.utility.CFUtil;
public class CONSTANTS {
public static final char[] SPACE = " ".toCharArray();
public static final char[] ZERO = "0".toCharArray();
public static final char[] SPACE_200 = CFUtil.fillSpaces(200);
public static final char[] EBCDIC_ENCODING = "cp1047".toCharArray();
public static final char[] FORMAT1016334848 = "----".toCharArray();
public static final char[] LITERAL_1079101867 = "Open POS_BOOKING Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_1775499624 = "SQLCODE = ".toCharArray();
public static final char[] LITERAL_452312193 = "Fetch POS_BOOKING Cursor failed : SQLCODE = ".toCharArray();
public static final char[] LITERAL_896462048 = "Update using POS_BOOKING Cursor failed : ".toCharArray();
public static final char[] LITERAL_APPLICATION_B9_ = "APPLICATION         ".toCharArray();
public static final char[] LITERAL_DATA_B16_ = "DATA                ".toCharArray();
public static final char[] LITERAL_SIZE = "SIZE".toCharArray();
public static final char[] LITERAL_SYSTEM_B14_ = "SYSTEM              ".toCharArray();
public static final char[] LITERAL_TRDPB002 = "TRDPB002".toCharArray();
public static final char[] LITERAL_TRDPBEXC = "TRDPBEXC".toCharArray();
 
}
