package com.edwardjones.app.common;
/* Java Code Generated by CloudFrame */ 
public class SQLS {
 
public static final char[] SQL_1273972904 = "SELECT POS_BALANCE FROM TBTRDPOS WHERE POS_CURRENCY = ? AND POS_SAC_NUMBER = ? AND POS_FIGI = ? FOR UPDATE OF POS_BALANCE".toCharArray() ;
public static final char[] SQL_150892171 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_150892171_1 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_150892171_2 = "INSERT INTO TBTRDEXC ( EXC_TYPE , EXC_DESCRIPTION ) VALUES ( ? , ? )".toCharArray() ;
public static final char[] SQL_950136353 = "UPDATE TBTRDPOS SET POS_BALANCE = ? WHERE POS_CURRENCY = ? AND POS_SAC_NUMBER = ? AND POS_FIGI = ?".toCharArray() ;
 
}
